// KeyFormat array in JavaScript, all units converted to metric (mm)
// All values are rounded to 3 decimal places where appropriate.
// Conversion: 1 inch = 25.4 mm
const KeyFormat = [
    {
        manufacturer: "Kwikset",
        format_name: "KW1",
        format_link: "https://lsamichigan.org/Tech/Kwikset_KeySpecs.pdf",
        first_pin_mm: 6.274,
        last_pin_mm: 21.518,
        pin_increment_mm: 3.81,
        pin_num: 5,
        pin_width_mm: 2.134,
        elbow_mm: 3.81,
        drill_angle: 90,
        uncut_depth_mm: 8.356,
        deepest_depth_mm: 4.851,
        depth_step_mm: 0.584,
        min_depth_ind: 1,
        max_depth_ind: 7,
        macs: 4,
        clearance: 3
    },
    {
        manufacturer: "Schlage",
        format_name: "SC4",
        format_link: "https://lsamichigan.org/Tech/SCHLAGE_KeySpecs.pdf",
        first_pin_mm: 5.867,
        last_pin_mm: 25.705,
        pin_increment_mm: 3.97,
        pin_num: 6,
        pin_width_mm: 0.787,
        elbow_mm: 2.54,
        drill_angle: 90,
        uncut_depth_mm: 8.509,
        deepest_depth_mm: 5.08,
        depth_step_mm: 0.381,
        min_depth_ind: 0,
        max_depth_ind: 9,
        macs: 7,
        clearance: 8
    },
    {
        manufacturer: "Arrow",
        format_name: "AR4",
        format_link: "C2",
        first_pin_mm: 6.731,
        last_pin_mm: 26.416,
        pin_increment_mm: 3.937,
        pin_num: 6,
        pin_width_mm: 1.524,
        elbow_mm: 2.54,
        drill_angle: 90,
        uncut_depth_mm: 7.925,
        deepest_depth_mm: 4.724,
        depth_step_mm: 0.356,
        min_depth_ind: 0,
        max_depth_ind: 9,
        macs: 6,
        clearance: 7
    },
    {
        manufacturer: "Master Lock",
        format_name: "M1",
        format_link: "C35",
        first_pin_mm: 4.699,
        last_pin_mm: 17.501,
        pin_increment_mm: 3.200,
        pin_num: 5,
        pin_width_mm: 0.991,
        elbow_mm: 2.54,
        drill_angle: 90,
        uncut_depth_mm: 7.010,
        deepest_depth_mm: 4.343,
        depth_step_mm: 0.381,
        min_depth_ind: 0,
        max_depth_ind: 7,
        macs: 7,
        clearance: 6
    },
    {
        manufacturer: "American",
        format_name: "AM7",
        format_link: "C80",
        first_pin_mm: 3.988,
        last_pin_mm: 19.839,
        pin_increment_mm: 3.175,
        pin_num: 6,
        pin_width_mm: 0.991,
        elbow_mm: 2.54,
        drill_angle: 90,
        uncut_depth_mm: 7.188,
        deepest_depth_mm: 4.394,
        depth_step_mm: 0.406,
        min_depth_ind: 1,
        max_depth_ind: 8,
        macs: 7,
        clearance: 5
    },
    {
        manufacturer: "Yale",
        format_name: "Y2",
        format_link: "C57",
        first_pin_mm: 5.08,
        last_pin_mm: 26.035,
        pin_increment_mm: 4.191,
        pin_num: 6,
        pin_width_mm: 1.372,
        elbow_mm: 2.54,
        drill_angle: 90,
        uncut_depth_mm: 8.128,
        deepest_depth_mm: 3.785,
        depth_step_mm: 0.483,
        min_depth_ind: 0,
        max_depth_ind: 9,
        macs: 9,
        clearance: 4
    },
    {
        manufacturer: "Yale",
        format_name: "Y11",
        format_link: "CX55",
        first_pin_mm: 3.150,
        last_pin_mm: 12.753,
        pin_increment_mm: 2.413,
        pin_num: 5,
        pin_width_mm: 0.991,
        elbow_mm: 2.54,
        drill_angle: 90,
        uncut_depth_mm: 6.248,
        deepest_depth_mm: 4.242,
        depth_step_mm: 0.508,
        min_depth_ind: 1,
        max_depth_ind: 5,
        macs: 7,
        clearance: 3
    },
    {
        manufacturer: "Sargent",
        format_name: "S22",
        format_link: "C44",
        first_pin_mm: 5.486,
        last_pin_mm: 25.298,
        pin_increment_mm: 3.962,
        pin_num: 6,
        pin_width_mm: 1.600,
        elbow_mm: 2.54,
        drill_angle: 90,
        uncut_depth_mm: 8.331,
        deepest_depth_mm: 3.759,
        depth_step_mm: 0.508,
        min_depth_ind: 1,
        max_depth_ind: 10,
        macs: 7,
        clearance: 5
    },
    {
        manufacturer: "National",
        format_name: "NA25",
        format_link: "C40",
        first_pin_mm: 6.350,
        last_pin_mm: 22.199,
        pin_increment_mm: 3.962,
        pin_num: 5,
        pin_width_mm: 0.991,
        elbow_mm: 2.54,
        drill_angle: 90,
        uncut_depth_mm: 7.722,
        deepest_depth_mm: 4.851,
        depth_step_mm: 0.305,
        min_depth_ind: 0,
        max_depth_ind: 9,
        macs: 7,
        clearance: 8
    },
    {
        manufacturer: "Corbin",
        format_name: "CO88",
        format_link: "C14",
        first_pin_mm: 6.350,
        last_pin_mm: 26.162,
        pin_increment_mm: 3.962,
        pin_num: 6,
        pin_width_mm: 1.194,
        elbow_mm: 2.54,
        drill_angle: 90,
        uncut_depth_mm: 8.712,
        deepest_depth_mm: 5.511,
        depth_step_mm: 0.356,
        min_depth_ind: 1,
        max_depth_ind: 10,
        macs: 7,
        clearance: 8
    },
    {
        manufacturer: "Lockwood",
        format_name: "LW4",
        format_link: "",
        first_pin_mm: 6.223,
        last_pin_mm: 22.098,
        pin_increment_mm: 3.97,
        pin_num: 5,
        pin_width_mm: 0.787,
        elbow_mm: 2.54,
        drill_angle: 90,
        uncut_depth_mm: 8.738,
        deepest_depth_mm: 5.156,
        depth_step_mm: 0.356,
        min_depth_ind: 0,
        max_depth_ind: 9,
        macs: 9,
        clearance: 8
    },
    {
        manufacturer: "Lockwood",
        format_name: "LW5",
        format_link: "",
        first_pin_mm: 6.223,
        last_pin_mm: 26.073,
        pin_increment_mm: 3.97,
        pin_num: 6,
        pin_width_mm: 0.787,
        elbow_mm: 2.54,
        drill_angle: 90,
        uncut_depth_mm: 8.738,
        deepest_depth_mm: 5.156,
        depth_step_mm: 0.356,
        min_depth_ind: 0,
        max_depth_ind: 9,
        macs: 9,
        clearance: 8
    },
    {
        manufacturer: "National",
        format_name: "NA12",
        format_link: "C39",
        first_pin_mm: 3.81,
        last_pin_mm: 18.034,
        pin_increment_mm: 3.556,
        pin_num: 5,
        pin_width_mm: 0.991,
        elbow_mm: 2.54,
        drill_angle: 90,
        uncut_depth_mm: 6.858,
        deepest_depth_mm: 3.988,
        depth_step_mm: 0.330,
        min_depth_ind: 0,
        max_depth_ind: 9,
        macs: 7,
        clearance: 8
    },
    {
        manufacturer: "Russwin",
        format_name: "RU45",
        format_link: "CX6",
        first_pin_mm: 6.350,
        last_pin_mm: 26.162,
        pin_increment_mm: 3.962,
        pin_num: 6,
        pin_width_mm: 1.346,
        elbow_mm: 2.54,
        drill_angle: 90,
        uncut_depth_mm: 8.712,
        deepest_depth_mm: 5.156,
        depth_step_mm: 0.711,
        min_depth_ind: 1,
        max_depth_ind: 6,
        macs: 5,
        clearance: 3
    },
    {
        manufacturer: "Weiser",
        format_name: "WR3",
        format_link: "https://www.lockwiki.com/index.php/Weiser_Classic",
        first_pin_mm: 6.019,
        last_pin_mm: 21.869,
        pin_increment_mm: 3.962,
        pin_num: 5,
        pin_width_mm: 2.286,
        elbow_mm: 3.81,
        drill_angle: 90,
        uncut_depth_mm: 8.001,
        deepest_depth_mm: 3.886,
        depth_step_mm: 0.457,
        min_depth_ind: 0,
        max_depth_ind: 10,
        macs: 6,
        clearance: 3
    },
    {
        manufacturer: "Ford",
        format_name: "H75",
        sides: 2,
        stop: 2,
        format_link: "CX101",
        first_pin_mm: 5.105,
        last_pin_mm: 21.463,
        pin_increment_mm: 2.337,
        pin_num: 8,
        pin_width_mm: 0.991,
        elbow_mm: 5.105,
        drill_angle: 90,
        uncut_depth_mm: 8.991,
        deepest_depth_mm: 6.451,
        depth_step_mm: 0.635,
        min_depth_ind: 1,
        max_depth_ind: 5,
        macs: 5,
        clearance: 2
    },
    {
        manufacturer: "Chevrolet",
        format_name: "B102",
        sides: 2,
        stop: 2,
        format_link: "",
        first_pin_mm: 5.207,
        last_pin_mm: 26.367,
        pin_increment_mm: 2.362,
        pin_num: 10,
        pin_width_mm: 0.991,
        elbow_mm: 5.207,
        drill_angle: 90,
        uncut_depth_mm: 8.001,
        deepest_depth_mm: 4.089,
        depth_step_mm: 0.660,
        min_depth_ind: 1,
        max_depth_ind: 4,
        macs: 5,
        clearance: 2
    },
    {
        manufacturer: "Dodge",
        format_name: "Y159",
        sides: 2,
        stop: 2,
        format_link: "CX102",
        first_pin_mm: 7.544,
        last_pin_mm: 23.901,
        pin_increment_mm: 2.337,
        pin_num: 8,
        pin_width_mm: 0.991,
        elbow_mm: 7.544,
        drill_angle: 90,
        uncut_depth_mm: 8.616,
        deepest_depth_mm: 5.004,
        depth_step_mm: 1.194,
        min_depth_ind: 1,
        max_depth_ind: 4,
        macs: 5,
        clearance: 1
    },
    {
        manufacturer: "Kawasaki",
        format_name: "KA14",
        sides: 2,
        format_link: "CMC50",
        first_pin_mm: 2.489,
        last_pin_mm: 15.011,
        pin_increment_mm: 2.489,
        pin_num: 6,
        pin_width_mm: 0.991,
        elbow_mm: 2.54,
        drill_angle: 90,
        uncut_depth_mm: 6.553,
        deepest_depth_mm: 5.029,
        depth_step_mm: 0.508,
        min_depth_ind: 1,
        max_depth_ind: 4,
        macs: 4,
        clearance: 3
    },
    {
        manufacturer: "Yamaha",
        format_name: "YM63",
        sides: 2,
        format_link: "CMC71",
        first_pin_mm: 3.988,
        last_pin_mm: 19.005,
        pin_increment_mm: 2.489,
        pin_num: 7,
        pin_width_mm: 0.991,
        elbow_mm: 2.54,
        drill_angle: 90,
        uncut_depth_mm: 7.493,
        deepest_depth_mm: 5.994,
        depth_step_mm: 0.508,
        min_depth_ind: 1,
        max_depth_ind: 4,
        macs: 4,
        clearance: 3
    },
    {
        manufacturer: "Best (A2)",
        format_name: "SFIC",
        stop: 2,
        format_link: "C3",
        first_pin_mm: 6.350,
        last_pin_mm: 25.349,
        pin_increment_mm: 3.785,
        pin_num: 6,
        pin_width_mm: 1.295,
        elbow_mm: 2.057,
        drill_angle: 90,
        uncut_depth_mm: 8.077,
        deepest_depth_mm: 5.232,
        depth_step_mm: 0.635,
        min_depth_ind: 0,
        max_depth_ind: 9,
        macs: 5,
        clearance: 3
    },
    {
        manufacturer: "RV (FIC,GL,Bauer)",
        format_name: "RV",
        sides: 2,
        format_link: "Card",
        first_pin_mm: 3.200,
        last_pin_mm: 12.806,
        pin_increment_mm: 2.388,
        pin_num: 5,
        pin_width_mm: 0.991,
        elbow_mm: 3.200,
        drill_angle: 90,
        uncut_depth_mm: 6.604,
        deepest_depth_mm: 4.597,
        depth_step_mm: 1.016,
        min_depth_ind: 1,
        max_depth_ind: 3,
        macs: 3,
        clearance: 1
    }
];
